version: "3"
services:
  frontend:
#    image: orfacello/itmo-cloud-frontend:v0
    profiles:
      - "full"
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_HOST=http://backend:8081
  backend:
    build: .
#    image: orfacello/itmo-cloud-backend:v0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud-dev
      - SPRING_DATASOURCE_USERNAME=itm00
      - SPRING_DATASOURCE_PASSWORD=qwerty
  db:
    image: "postgres:10-alpine"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=itm00
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=cloud-dev
