name: Docker Image CI

on:
  push:
    branches: [ deploy ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
          
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.1.6
      with:
        arguments: build

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag orfacello/itmo-cloud-backend:v0

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: orfacello
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker push orfacello/itmo-cloud-backend:v0

